spring:
  application:
    name: msone
  jpa:
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backend
    username: backend
    password: backend
    hikari:
      auto-commit: false
      maximum-pool-size: 3
      connection-timeout: 30000
      idle-timeout: 10000
  flyway:
    enabled: true
    locations: classpath:db/migration/structure,classpath:db/migration/data
    validate-on-migrate: true
    default-schema: public
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
  servlet:
    context-path: /msone