spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: springgateway
  cloud:
    discovery:
      enabled: true
    gateway:
      enabled: true
      routes:
        - id: msone
          uri: lb://MSONE
          predicates:
            - Path=/api/v1/**
          filters:
            - UpdateExchangeGatewayPostFilter=

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8484/realms/architec-project-local
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

