spring:
  application:
    name: springgateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: msone
          uri: lb://msone
          predicates:
            - Path=/asd/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

